namespace UE4Decompiler.Output.Writer;

/// <summary>A synthesized EdGraphPin (subset needed to reconstruct K2 graphs).</summary>
public sealed class SynthPin
{
    public int OwningNodePkg;                 // FPackageIndex of the owning node export
    public FGuid16 PinId = FGuid16.NewGuid();
    public string PinName = "";
    public string Category = "exec";          // PinCategory (exec / int / object / …)
    public string SubCategory = "";
    public int SubCategoryObjPkg = 0;         // FPackageIndex of PinSubCategoryObject (e.g. a class)
    public byte Direction;                    // EGPD_Input=0, EGPD_Output=1
    public string DefaultValue = "";
    public int DefaultObjPkg = 0;
    public readonly List<(int owningNodePkg, FGuid16 pinId)> LinkedTo = new();
}

/// <summary>
/// [Tier2 Phase 4 — module #2] Serializes EdGraph pins exactly as UE4.21 UEdGraphNode::Serialize does
/// (EdGraphPin.cpp). Owning-node pins write the full body; LinkedTo entries are deferred refs
/// (bNullPtr + OwningNode + PinId). Custom versions FFrameworkObjectVersion(PinsStoreFName,
/// EdGraphPinContainerType) are assumed present in the package (they are — Dev-Framework=34).
/// </summary>
public sealed class PinSerializer
{
    private readonly FArchiveWriter _w;
    private readonly Func<string, int> _name;
    public PinSerializer(FArchiveWriter w, Func<string, int> nameAdder) { _w = w; _name = nameAdder; }

    // Empty FName fields serialize as NAME_None ("None"), NOT as an empty-string name entry —
    // injecting "" into the name table corrupts later length reads (Assertion SerializeNum>=0).
    private void FName(string s) { var n = string.IsNullOrEmpty(s) ? "None" : s; _w.Write(_name(n)); _w.Write(0); }
    private void ArchiveBool(bool b) => _w.Write(b ? 1 : 0);     // FArchive bool = int32 (4 bytes)
    private void Guid(FGuid16 g) { _w.Write(g.A); _w.Write(g.B); _w.Write(g.C); _w.Write(g.D); }
    private void TextEmpty() { _w.Write(0u); _w.Write((byte)0xFF); }  // Flags=0, HistoryType=INDEX_NONE(-1)

    /// <summary>UEdGraphNode::Serialize writes one int32 (0) after the tagged-prop None and before the
    /// pin array (observed in ground-truth 4.21 K2Node bytes), then UEdGraphPin::SerializeAsOwningNode
    /// writes int32 count + full body per pin.</summary>
    public void WriteOwningPins(IReadOnlyList<SynthPin> pins)
    {
        _w.Write(0);                 // leading int32 before pin array (matches real editor output)
        _w.Write(pins.Count);
        foreach (var p in pins) WriteOwningPin(p);
    }

    private void WriteOwningPin(SynthPin p)
    {
        // SerializePin header (owning): bNullPtr + OwningNode + PinId
        ArchiveBool(false);
        _w.Write(p.OwningNodePkg); Guid(p.PinId);
        // UEdGraphPin::Serialize body (note: OwningNode + PinId written AGAIN per engine)
        _w.Write(p.OwningNodePkg); Guid(p.PinId);
        FName(p.PinName);
        TextEmpty();                         // PinFriendlyName (editor, not filtered)
        _w.WriteFString("");                 // PinToolTip
        _w.Write(p.Direction);               // TEnumAsByte (1 byte)
        WritePinType(p);
        _w.WriteFString(p.DefaultValue);     // DefaultValue
        _w.WriteFString("");                 // AutogeneratedDefaultValue
        _w.Write(p.DefaultObjPkg);           // DefaultObject (objref)
        TextEmpty();                         // DefaultTextValue
        // LinkedTo (deferred refs)
        _w.Write(p.LinkedTo.Count);
        foreach (var (node, id) in p.LinkedTo) { ArchiveBool(false); _w.Write(node); Guid(id); }
        _w.Write(0);                         // SubPins count
        ArchiveBool(true);                   // ParentPin = null (bNullPtr=true)
        ArchiveBool(true);                   // ReferencePassThroughConnection = null
        Guid(FGuid16.NewGuid());             // PersistentGuid
        _w.Write(0u);                        // BitField (hidden/notConnectable/… = 0)
    }

    private void WritePinType(SynthPin p)
    {
        FName(p.Category);                   // PinCategory
        FName(p.SubCategory);                // PinSubCategory
        _w.Write(p.SubCategoryObjPkg);       // PinSubCategoryObject (objref)
        _w.Write((byte)0);                   // ContainerType (EPinContainerType::None)
        ArchiveBool(false);                  // bIsReference
        ArchiveBool(false);                  // bIsWeakPointer
        // PinSubCategoryMemberReference (FSimpleMemberReference): MemberParent + MemberName + MemberGuid
        _w.Write(0);                         // MemberParent (objref null)
        FName("None");                       // MemberName
        Guid(default);                       // MemberGuid (zero)
        ArchiveBool(false);                  // bIsConst
    }
}
